variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

stages:
  - test
  - deploy

test:
  image: python:3.6
  stage: test
  script:
    - echo "============== Testing Package ============="
    - pip install .
    - pip list
    - python setup.py test
    - echo "============================================"

deploy:
  image: python:3.6
  stage: deploy
  script:
    - pip install -U twine setuptools
    - pip list
    - python setup.py sdist bdist_wheel
    - echo "======== Deploying Package to PyPi ========="
    - twine upload dist/*
    - echo "============================================"
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
