variables:
    PYPI_USERNAME: SECURE
    PYPI_PASSWORD: SECURE

stages:
  - test
  - deploy

test:
  image: python:3.6
  stage: test
  script:
    - echo "============== Testing Package ============="
    - pip install .
    - pip list
    - python setup.py test
    - echo "============================================"

deploy:
  image: python:3.6
  stage: deploy
  script:
    - pip install -U twine setuptools
    - pip list
    - python setup.py sdist bdist_wheel
    - echo "======== Deploying Package to PyPi ========="
    - "printf \"[distutils]\nindex-servers =\n   testpypi\n\n[testpypi]\nrepository: https://test.pypi.org/legacy/\nusername=$PYPI_USERNAME\npassword=asdf\n\" > ~/.pypirc"
    - cat ~/.pypirc
    - twine upload --repository-url "https://test.pypi.org/legacy/" dist/*
    - echo "============================================"
