variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    ANACONDA_USERNAME: SECURE
    ANACONDA_TOKEN: SECURE
    DOCKER_PASSWORD: SECURE
    DOCKER_USERNAME: SECURE

stages:
  - test
  - deploy
  - docs

test:
  image: python:3.6
  stage: test
  script:
    - pip install .
    - python setup.py test --addopts "--cov=pypkgtemp"

deploy_pypi:
  image: python:3.6
  stage: deploy
  script:
    - pip install -U twine setuptools
    - python setup.py sdist bdist_wheel
    - twine upload dist/*.tar.gz
    - twine upload dist/*.whl
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)


deploy_conda:
  image: continuumio/miniconda3:latest
  stage: deploy
  script:
    - conda install anaconda-client setuptools conda-build -y
    - python setup.py bdist_conda
    - anaconda -t $ANACONDA_TOKEN upload -u $ANACONDA_USERNAME /opt/conda/conda-bld/linux-64/pypkgtemp*.tar.bz2
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)


deploy_docker:
  image: docker:git
  stage: deploy
  services:
    - docker:dind
  script:
    - docker build -t python-package-template:$CI_COMMIT_TAG --build-arg VERSION=$CI_COMMIT_TAG .
    # push to dockerhub
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag python-package-template:$CI_COMMIT_TAG costrouc/python-package-template:$CI_COMMIT_TAG
    - docker tag python-package-template:$CI_COMMIT_TAG costrouc/python-package-template:latest
    - docker push costrouc/python-package-template:$CI_COMMIT_TAG
    - docker push costrouc/python-package-template:latest
    # push to gitlab registry
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker tag python-package-template:$CI_COMMIT_TAG registry.gitlab.com/costrouc/python-package-template:$CI_COMMIT_TAG
    - docker tag python-package-template:$CI_COMMIT_TAG registry.gitlab.com/costrouc/python-package-template:latest
    - docker push registry.gitlab.com/costrouc/python-package-template:$CI_COMMIT_TAG
    - docker push registry.gitlab.com/costrouc/python-package-template:latest
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)

pages:
  image: python:3.6
  stage: docs
  script:
    - pip install sphinx sphinx_rtd_theme
    - pip install -e .
    - mkdir public
    - cd docs
    - make apidocs
    - make html
    - cp -r _build/html/* ../public
  artifacts:
    paths:
      - public
  only:
    - master
