language: python
cache: pip
python:
- '3.7'

install:
  - make init
  - source $HOME/.poetry/env

jobs:
  include:
    - stage: test
      script:
        - source $HOME/.poetry/env
        - make test

notifications:
  email:
    on_failure: never

