language: python
cache: pip

jobs:
  include:
    - name: "Python 3.8 on Focal"
      python: 3.8
      dist: focal

services:
  - redis-server

install:
  - python3 -m pip install -U pip
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env
  - make init

script:
  - source $HOME/.poetry/env
  - make test

notifications:
  email:
    on_failure: never
