language: python
cache: pip
python:
- '3.7'

install:
  - python3 -m pip install -U pip
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - source $HOME/.poetry/env
  - make init

jobs:
  include:
  - stage: test
    script:
    - source $HOME/.poetry/env
    - make test

notifications:
  email:
    on_failure: never
