* KnoxPy Summary

  This presentation will follow the story of a developer wanting to
  create a python package for analyzing attempted ssh logins to their
  home machine using an [[https://sqlite.org/index.html][SQLite3]] database. In the end we will have
  created a continuously delivered [[https://pypi.org/][PyPi]] package that has documentation
  on [[https://readthedocs.org/][readthedocs]] generated with [[http://www.sphinx-doc.org/en/stable/][sphinx]] and tested via [[https://docs.pytest.org/en/latest/][pytest]].

  The talk will focus on showing the power of =sqlite3= [[https://docs.python.org/3/library/sqlite3.html][module]] in the
  python standard library. I will not assume that the user has used
  =SQL= before and show examples of simple =SELECT=, =INSERT=, =CREATE
  TABLE=, transactions, bulk inserts for performance, and how to
  determine if SQLite3 is the correct database to use.

  For advanced users this talk will still have equal benefit. I will
  show how to use custom [[https://www.sqlite.org/datatype3.html][SQLite datatypes]] for serialization and
  deserialization of datetimes and JSON. Additionally, using a unique
  feature of SQLite we will create python functions for queries not
  possible with complex SQL statements.

  This talk will be based on two of my blog posts
    - [[https://chrisostrouchov.com/post/python_sqlite/][sqlite with python]]
    - [[https://chrisostrouchov.com/post/cd_tested_doc_pypi_package/][continuous delivery, tested, and documented pypi packages]]
      (currently drafted will be available mid April)

  Packages Used:
    - sqlite3 (detailed)
    - pytest (brief)
    - sphinx (brief)
    - setuptools (brief)

  All source code and documents will be available in the [[https://gitlab.com/costrouc/knoxpy-sqlite-pypi-readthedocs][Gitlab repo]]
